/**
 * Generate src/ottl/catalog.ts from the upstream OTTL function reference, so the
 * linter's known-function list never drifts from the real language.
 *
 * Source of truth:
 *   opentelemetry-collector-contrib/pkg/ottl/ottlfuncs/README.md
 *   (## Editors / ## Converters sections, one `### <name>` heading per function)
 *
 * Usage:
 *   node scripts/gen-catalog.mjs <path-to-ottlfuncs-README.md>
 *
 * Get the README from a local checkout of the contrib repo, or download the raw
 * file yourself and pass the local path. (We intentionally read a local file
 * rather than fetching at runtime, so the build is reproducible and offline.)
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const readmePath = process.argv[2];
if (!readmePath) {
  console.error("usage: node scripts/gen-catalog.mjs <path-to-ottlfuncs-README.md>");
  process.exit(2);
}

const text = readFileSync(readmePath, "utf8");
const lines = text.split(/\r?\n/);

const editors = new Set();
const converters = new Set();
let section = null;

for (const line of lines) {
  const h2 = /^##\s+(.+?)\s*$/.exec(line);
  if (h2) {
    const title = h2[1].toLowerCase();
    if (title === "editors") section = "editors";
    else if (title === "converters") section = "converters";
    else section = null;
    continue;
  }
  const h3 = /^###\s+(.+?)\s*$/.exec(line);
  if (h3 && section) {
    const name = (/^([A-Za-z_][A-Za-z0-9_]*)/.exec(h3[1]) || [])[1];
    if (!name) continue;
    (section === "editors" ? editors : converters).add(name);
  }
}

if (editors.size === 0 || converters.size === 0) {
  console.error(
    `parse error: editors=${editors.size} converters=${converters.size}. ` +
      `Check the README has '## Editors' and '## Converters' sections.`
  );
  process.exit(1);
}

const sort = (s) => [...s].sort((a, b) => a.localeCompare(b));
const lit = (arr) => arr.map((n) => `  ${JSON.stringify(n)}`).join(",\n");

const out = `// AUTO-GENERATED by scripts/gen-catalog.mjs — do not edit by hand.
// Source: pkg/ottl/ottlfuncs/README.md (upstream OTTL function reference).
// Generated: ${new Date().toISOString().slice(0, 10)} · editors=${editors.size} converters=${converters.size}
//
// Editors  = functions that MUTATE telemetry (statement position).
// Converters = functions that RETURN a value. Names are case-sensitive.

export const EDITORS: ReadonlySet<string> = new Set([
${lit(sort(editors))}
]);

export const CONVERTERS: ReadonlySet<string> = new Set([
${lit(sort(converters))}
]);

export const KNOWN_FUNCTIONS: ReadonlySet<string> = new Set<string>([
  ...EDITORS,
  ...CONVERTERS
]);

export const CASEFOLD_INDEX: ReadonlyMap<string, string> = new Map(
  [...KNOWN_FUNCTIONS].map((name) => [name.toLowerCase(), name])
);
`;

const target = resolve(__dirname, "..", "src", "ottl", "catalog.ts");
writeFileSync(target, out, "utf8");
console.log(
  `wrote ${target}\n  editors=${editors.size} converters=${converters.size} total=${
    editors.size + converters.size
  }`
);
